CoreMigroup/Models/FileUpload.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace CoreMigroup.Models
{
    public class FileUpload : Base
    {
        public int FolderId { get; set; } = 0;
        public string DuongDan { get; set; } = "";
        public int KichThuoc { get; set; } = 0;
        public int SoLuotTai { get; set; } = 0;
        public int SoLuotXem { get; set; } = 0;
        public string DuoiFile { get; set; } = "";
        public string Avatar { get; set; } = "";


        [ForeignKey("FolderId")]
        public virtual Folder GetFolder { get; set; }

    }
}

CoreMigroup/Controllers/FileUploadsController.cs
using CoreMigroup.Helper;
using CoreMigroup.Models;
using CoreMigroup.Repository.FileUploadRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace CoreMigroup.Controllers
{
    [Authorize]
    public class FileUploadsController : BaseController
    {
        private IFileUploadRepository _fileUploadRepository;
        private ICrawlingExcelHelper _crawling;
        public FileUploadsController(IFileUploadRepository fileUploadRepository, ICrawlingExcelHelper crawling)
        {
            _fileUploadRepository = fileUploadRepository;
            _crawling = crawling;
        }
        [Authorize(Roles = "Admin,HienThiMenuFile,XemDanhSachFile")]
        
        public IActionResult GetList()
        {
            return View();
        }
        //[Authorize(Roles = "Admin,HienThiMenuFile")]
        [HttpPost]

        public IActionResult LoadFilesInFolder(int folderId)
        {
            return ViewComponent("FileInFolder", new { folderId = folderId });
        }
        [HttpPost]
        public IActionResult Find(int[] folderId, DateTime startDate, DateTime endDate, string keyword)
        {


            List<IQueryable<FileUpload>> lstFile = new List<IQueryable<FileUpload>>();
            var allFile = _fileUploadRepository.GetAll();
            allFile = allFile.Where(x =>
            (folderId.Length > 0 && folderId.Select(y => y).Contains(x.FolderId))
            || (keyword != null && x.Ten.ToLower().Trim().Contains(keyword.ToLower().Trim()))
            || (x.NgayTao >= startDate && x.NgayTao <= endDate));

            allFile = allFile.Include(r => r.GetFolder).Include(r => r.GetNguoiTao).Where(r => r.IsDaXoa != true);


            return View("~/Views/FileUploads/Components/ListFileUploads.cshtml", allFile.ToList());
        }
        //[Authorize(Roles = "Admin,HienThiMenuFile")]
        [HttpPost]
        public IActionResult FilterFiles(param_GetFileUpload request)
        {
            return ViewComponent("ListFileUploads", new { request = request });
        }
        [HttpPost]
        public IActionResult ViewAddEditFileUpload(int id)
        {
            return ViewComponent("AddorUpdateFileUpload", new { id = id });
        }

        [HttpPost]
        public async Task<IActionResult> AddOrUpdateFileUpload_DangKyDoanhNghiep([FromForm] param_SaveFileUpload request)
        {
            var responseData = new ResponseData<FileUpload>();
            if(request != null)
            {
                if(request.lsFiles.Count <= 0 && request.id == 0)
                {
                    responseData.IsSuccess = false;
                    responseData.ErrorMessage = "Không có file được chọn";
                    return BadRequest(responseData);
                }
                else if (string.IsNullOrEmpty(request.tenFile))
                {
                    responseData.IsSuccess = false;
                    responseData.ErrorMessage = "Tên file không được để trống";
                    return BadRequest(responseData);
                }
                else if (request.danhMucFile == 0 && string.IsNullOrEmpty(request.danhMucTen))
                {
                    responseData.IsSuccess = false;
                    responseData.ErrorMessage = "Mời chọn danh mục file";
                    return BadRequest(responseData);
                }
                else
                {
                    var r = await _fileUploadRepository.AddOrUpdateFileUpload_ExcelDoanhNghiep(request);
                    responseData.IsSuccess = true;
                    responseData.Datas.Add(r);
                    return Ok(responseData);
                }
            }
            responseData.IsSuccess = false;
            responseData.ErrorMessage = "Request không hợp lệ";
            return BadRequest(responseData);
        }

        [HttpPost]
        public async Task<IActionResult> DongBoDuLieu_DoanhNghiep(int id)
        {
            var responseData = new ResponseData<int>();
            if(id > 0)
            {
                var totalRecord = await _crawling.ImportExcelDoanhNghiepAsync(id);
                if(totalRecord > 0)
                {
                    responseData.IsSuccess = true;
                    responseData.TotalRecord = totalRecord;
                    return Ok(responseData);
                }
            }
            responseData.IsSuccess = false;
            responseData.ErrorMessage = "Có lỗi xảy ra! Vui lòng thử lại";
            return BadRequest(responseData);
        }
    }
}

    

CoreMigroup/ViewComponents/FileUploads/AddorUpdateFileUploadViewComponent.cs
using CoreMigroup.Models;
using CoreMigroup.Repository.FileUploadRepository;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoreMigroup.ViewComponents.FileUploads
{
    public class AddorUpdateFileUploadViewComponent : ViewComponent
    {
        private IFileUploadRepository _fileUploadRepository;
        public AddorUpdateFileUploadViewComponent(IFileUploadRepository fileUploadRepository)
        {
            _fileUploadRepository = fileUploadRepository;
        }
        public IViewComponentResult Invoke(int id)
        {
            var model = new FileUpload();
            if (id > 0)
                model = _fileUploadRepository.GetById(id);
            return View("~/Views/FileUploads/Components/SaveFileUpload.cshtml", model);
        }
    }
}

CoreMigroup/ViewComponents/FileUploads/ListFileUploadsViewComponent.cs
using CoreMigroup.Enum;
using CoreMigroup.Repository.FileUploadRepository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoreMigroup.ViewComponents.FileUploads
{
    public class ListFileUploadsViewComponent : ViewComponent
    {
        private IFileUploadRepository _fileUploadRepository;
        public ListFileUploadsViewComponent(IFileUploadRepository fileUploadRepository)
        {
            _fileUploadRepository = fileUploadRepository;
        }
        public IViewComponentResult Invoke(param_GetFileUpload request)
        {

            var model = _fileUploadRepository.GetAll().Include(r => r.GetFolder).Include(r => r.GetNguoiTao)
                .Where(r => r.IsDaXoa != true).Where(r => r.Loai == (int)LoaiFileEnum.Excel);
            if (request.FolderIds.Count > 0)
                model = model.Where(r => request.FolderIds.Contains(r.FolderId));
            if (request.NgayUploadTu != null)
                model = model.Where(r => r.NgayTao >= request.NgayUploadTu.Value);
            if (request.NgayUploadDen != null)
                model = model.Where(r => r.NgayTao <= request.NgayUploadDen.Value);
            if (!string.IsNullOrEmpty(request.Keyword))
                model = model.Where(r => r.Ten.Contains(request.Keyword) || r.Ma.Contains(request.Keyword) || r.GetFolder.Ma.Contains(request.Keyword) || r.GetFolder.Ten.Contains(request.Keyword));
            var total = model.Count();
            if (request.Index.Value > 0 && request.Size.Value > 0)
                model = model.OrderByDescending(r => r.NgayTao).Skip((request.Index.Value - 1) * request.Size.Value).Take(request.Size.Value);
            
            
            ViewBag.Total = total;
            ViewBag.Index = request.Index.Value;
            ViewBag.Size = request.Size.Value;

            return View("~/Views/FileUploads/Components/ListFileUploads.cshtml", model.ToList());
        }
    }
}

CoreMigroup/Views/FileUploads/GetList.cshtml
@using CoreMigroup.Repository.FileUploadRepository;
@using CoreMigroup.Repository.FolderRepository;
@using CoreMigroup.Repository.UserRoleRepository;
@using CoreMigroup.Helper;
@using CoreMigroup.Enum;
@inject IFileUploadRepository _fileRepo;
@inject IFolderRepository _folderRepo;
@inject IUserRoleRepository _userRoleRepo;
@inject IUserHelper _userHelper;
@{
    ViewData["Title"] = "GetList";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var user = _userHelper.GetCurrentUserAsync().Result;
}

@section styles{
    <style>
        #quan-ly-files-modal .modal {
            position: relative;
            top: auto;
            bottom: auto;
            right: auto;
            left: auto;
            display: block;
            z-index: 1;
        }

        #quan-ly-files-modal .modal {
            background: transparent !important;
        }
    </style>
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Danh sách file

        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Examples</a></li>
            <li class="active">Blank page</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="box">
            <div class="box-header with-border">
                <div class="row">
                    <div class="col-md-9 col-sm-12">
                        <div class="row">
                            <div class="col-md-4">
                                <label for="search-folder">
                                    Danh mục file
                                </label>
                                <select class="form-control" id="slb-folder-search" multiple="multiple" name="search-folder" data-placeholder="Chọn Folder"
                                        style="width: 100%;">
                                    @{
                                        var lsFolder = _folderRepo.GetAll().Where(r => r.IsDaXoa != true);
                                        foreach (var item in lsFolder)
                                        {
                                            <option value="@item.Id">@item.Ten</option>
                                        }
                                    }
                                </select>
                            </div>
                            <div class="col-md-4">
                                <label for="search-thoi-gian-upload">
                                    Thời gian
                                </label>
                                <div class="input-group" name="search-thoi-gian-upload">
                                    <div class="input-group-addon">
                                        <i class="fa fa-calendar"></i>
                                    </div>
                                    <input type="text" class="form-control pull-right" id="txb-thoi-gian-upload">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <label for="search-folder">
                                    Keyword
                                </label>
                                @*<input type="text" name="search-folder" id="txtSearch" class="form-control" placeholder="Nhập keyword cần tìm kiếm" />*@
                                <input type="text" name="search-folder" class="form-control" id="txb-keyword-file-upload" placeholder="Nhập keyword cần tìm kiếm" />
                            </div>
                        </div>

                    </div>
                    <div class="col-md-3 col-sm-12">
                        <label for="group-button-action">Hành động <br /></label>
                        <div class="btn-group" name="group-button-action">



                            @if (_userRoleRepo.CheckRoleByRoleNameAndUserId(user.Id, TenRoleEnum.Admin.ToString()))
                            {


                                <button type="button" class="btn btn-default btn-flat" id="btn-tim-kiem-file"><i class="fa fa-search"></i></button>
                                <button type="button" class="btn btn-default btn-flat" id="create-file-upload"><i class="fa fa-upload"></i></button>
                                <button type="button" class="btn btn-default btn-flat delete_file "><i class="fa fa-trash"></i></button>
                            }
                            else
                            {
                                <button type="button" class="btn btn-default btn-flat" id="btn-tim-kiem-file"><i class="fa fa-search"></i></button>
                                @*<button type="button" class="btn btn-default btn-flat open-upload-files-component"><i class="fa fa-upload"></i></button>*@
                                @*<button type="button" class="btn btn-default btn-flat delete_file "><i class="fa fa-trash"></i></button>*@
                            }


                        </div>
                    </div>
                </div>

            </div>
            <div class="box-body table-responsive no-padding binding-data " id="tbl-file-upload">
                @*@await Component.InvokeAsync("ListFileUploads", new { request = new param_GetFileUpload() })*@
            </div>

            <!-- /.box-body -->
            <div class="box-footer clearfix">
                <div class="binding-phan-trang"></div>

                <ul class="pagination pagination-sm no-margin pull-right">

                    @*<li><a href="javascript:void(0)">«</a></li>
            <li><a href="javascript:void(0)">1</a></li>
            <li><a href="javascript:void(0)">2</a></li>
            <li><a href="javascript:void(0)">3</a></li>
            <li><a href="javascript:void(0)">»</a></li>*@

                </ul>
            </div>
            <!-- /.box-footer-->
        </div>
        <!-- /.box -->

    </section>
    <!-- /.content -->
</div>
<div class="modal fade" id="save-file-upload-modal">

</div>
@await Component.InvokeAsync("QuanLyFile")
@section scripts{
    <script src="~/js/controller/fileUploadsController.js"></script>
}