CoreMigroup/Controllers/UsersController.cs
using CoreMigroup.Helper;
using CoreMigroup.Models;
using CoreMigroup.Repository.UserRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoreMigroup.Controllers
{
    [Authorize]
    public class UsersController : BaseController
    {
        private IUserRepository _repo;
        public UsersController(IUserRepository repo)
        {
            _repo = repo;
        }
        [Authorize(Roles = "Admin,HienThiMenuUser")]
        public IActionResult ListUser()
        {
            return View();
        }
        [HttpPost]
        public IActionResult GetListUser(param_FilterUser request)
        {
            return ViewComponent("GetListUsers", new { request = request});
        }
        public IActionResult ModalGetById(int userId)
        {
            return ViewComponent("GetById", new { userId = userId });
        }

    }
}

CoreMigroup/ViewComponents/Users/GetByIdViewComponent.cs
using CoreMigroup.Data;
using CoreMigroup.Repository.UserRepository;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoreMigroup.ViewComponents.Users
{
    public class GetByIdViewComponent : ViewComponent
    {
        private IUserRepository _userdRepository;
        private ApplicationDbContext _db;
        public GetByIdViewComponent(IUserRepository userdRepository, ApplicationDbContext db)
        {
            _userdRepository = userdRepository;
            _db = db;
        }
        public IViewComponentResult Invoke(int userId)
        {
            //var allRows = _db.Users.ToList();
            ViewBag.UserId = userId;
            var id = _db.Users.SingleOrDefault(x => x.Id == userId);
            
            return View("~/Views/Users/Components/GetById.cshtml", id);
        }
    }
}

CoreMigroup/ViewComponents/Users/GetListUsersViewComponent.cs
using CoreMigroup.Repository.UserRepository;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoreMigroup.ViewComponents.Users
{
    public class GetListUsersViewComponent : ViewComponent
    {
        private IUserRepository _userdRepository;
        public GetListUsersViewComponent(IUserRepository userdRepository)
        {
            _userdRepository = userdRepository;
        }
        public IViewComponentResult Invoke(param_FilterUser request)
        {

            var t = 0;
            var res = _userdRepository.GetList(request, out t);

            ViewBag.Total = t;
            ViewBag.Index = request.Index.Value;
            ViewBag.Size = request.Size.Value;

            return View("~/Views/Users/Components/GetListUser.cshtml", res);
        }
    }
}

CoreMigroup/ViewComponents/Users/PhanQuyenViewComponent.cs
using CoreMigroup.Data;
using CoreMigroup.Repository.UserRepository;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoreMigroup.ViewComponents.Users
{
    public class PhanQuyenViewComponent : ViewComponent
    {
        private IUserRepository _userdRepository;
        private ApplicationDbContext _db;
        public PhanQuyenViewComponent(IUserRepository userdRepository, ApplicationDbContext db)
        {
            _userdRepository = userdRepository;
            _db = db;
        }
        public IViewComponentResult Invoke(int userId)
        {
            var allRows = _db.Roles.ToList();
            ViewBag.UserId = userId;

            return View("~/Views/Users/Components/PhanQuyen.cshtml", allRows);
        }
    }
}

CoreMigroup/Views/Users/ListUser.cshtml
@using CoreMigroup.Repository.FileUploadRepository
@using CoreMigroup.Repository.FolderRepository;
@using CoreMigroup.Repository.UserRepository;
@inject IFileUploadRepository _fileRepo;
@inject IFolderRepository _folderRepo;

@{
    ViewData["Title"] = "GetList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section styles{
    <style>
        #phan-quyen-user-modal .modal {
            position: relative;
            top: auto;
            bottom: auto;
            right: auto;
            left: auto;
            display: block;
            z-index: 1;
        }

        #phan-quyen-user-modal .modal {
            background: transparent !important;
        }
    </style>
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Danh sách user

        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Examples</a></li>
            <li class="active">Blank page</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="box">
            <div class="box-header with-border">
                <div class="row">
                    <div class="col-md-9 col-sm-12">
                        <div class="row">
                            <div class="col-md-4">
                                <label for="search-folder">
                                    Keyword
                                </label>
                                <input type="text" name="search-folder" class="form-control" id="txb-keyword-user" placeholder="Nhập keyword cần tìm kiếm" />
                            </div>
                        </div>

                    </div>
                    <div class="col-md-3 col-sm-12">
                        <label for="group-button-action">Hành động <br /></label>
                        <div class="btn-group" name="group-button-action">
                            <button type="button" class="btn btn-default btn-flat" id="btn-tim-kiem-user"><i class="fa fa-search"></i></button>
                            @*<button type="button" class="btn btn-default btn-flat open-upload-files-component"><i class="fa fa-upload"></i></button>
                                <button type="button" class="btn btn-default btn-flat"><i class="fa fa-trash"></i></button>*@
                        </div>
                    </div>
                </div>

                @*<div class="box-tools pull-left">


                    </div>*@
            </div>
            <div class="box-body table-responsive no-padding binding-data">
                @await Component.InvokeAsync("GetListUsers", new { request = new param_FilterUser() })
            </div>

            <!-- /.box-body -->
            <div class="box-footer clearfix">
                <div class="binding-phan-trang"></div>
                
                    <ul class="pagination pagination-sm no-margin pull-right">

                        @*<li><a href="javascript:void(0)">«</a></li>
                        <li><a href="javascript:void(0)">1</a></li>
                        <li><a href="javascript:void(0)">2</a></li>
                        <li><a href="javascript:void(0)">3</a></li>
                        <li><a href="javascript:void(0)">»</a></li>*@
                    
                </ul>
            </div>
            <!-- /.box-footer-->
        </div>
        <!-- /.box -->

    </section>
    <!-- /.content -->
</div>
<div class="modal fade" id="phan-quyen-user-modal">
    @await Component.InvokeAsync("PhanQuyen")
</div>

<!-- Modal -->
<div class="modal fade" id="getbyid-modal" role="dialog">
    @*@await Component.InvokeAsync("GetById")*@
</div>



@*@await Component.InvokeAsync("QuanLyFile")*@
@section scripts{
    <script src="~/js/controller/quanLyUserController.js"></script>
    @*<script src="~/js/controller/userController.js"></script>*@

}