CoreMigroup/ViewComponents/CommonComponent/QuanLyFile/FileInFolderViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoreMigroup.ViewComponents
{
    public class FileInFolderViewComponent :ViewComponent
    {
        public IViewComponentResult Invoke(int folderId)
        {
            ViewBag.FolderId = folderId;
            return View("~/Views/Shared/Components/QuanLyFile/FileInFolder.cshtml");
        }
    }
}

CoreMigroup/ViewComponents/CommonComponent/QuanLyFile/QuanLyFileViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoreMigroup.ViewComponents
{
    public class QuanLyFileViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke() {
            ViewBag.Test = 1;
            return View("~/Views/Shared/Components/QuanLyFile/QuanLyFile.cshtml");
        }
    }
}

CoreMigroup/Views/Shared/Components/QuanLyFile/FileInFolder.cshtml
@using CoreMigroup.Repository.FileUploadRepository
@inject IFileUploadRepository _fileUploadRepo
@{
    var folderId = (int)ViewBag.FolderId;
    //var lsFile = _fileUploadRepo.GetByCondition(expression: b => b.FolderId == folderId, out t, false, 1, 9);
    var lsFile = _fileUploadRepo.GetAll().Where(r => r.FolderId == folderId).ToList();
}

<div class="row">

    @foreach (var item in lsFile)
    {
        <div class="col-md-3">
            <a href="javascript:void(0)" data-url="@item.DuongDan" class="select-file-in-folder">
                <img src="@item.Avatar" style="max-width:100%; max-height:150px" />
                <div class="info-file">
                    <p style="word-wrap: break-word;">@item.Ten</p>
                </div>
            </a>
        </div>
    }

</div>

CoreMigroup/Views/Shared/Components/QuanLyFile/QuanLyFile.cshtml
@using CoreMigroup.Repository.FolderRepository;
@using CoreMigroup.Helper;
@inject IUserHelper _userHelper;
@inject IFolderRepository _folderRepo;
<div class="modal fade" id="quan-ly-files-modal">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">Info Modal</h4>
            </div>
            <div class="modal-body">
                <!-- Content Header (Page header) -->
                <section class="content-header">
                    <h1>
                        User Profile
                    </h1>
                    <ol class="breadcrumb">
                        <li><form id="form-upload-files"><input type="file" id="input-upload-files" multiple style="display:none;" /><button type="button" class="btn btn-default" id="button-upload-files">Upload</button></form></li>
                        @*<li><button type="button" class="btn btn-default">Delete</button></li>*@
                    </ol>
                </section>
                <!-- Main content -->
                <section class="content">

                    <div class="row">
                        <div class="col-md-3">

                            <!-- Profile Image -->
                            <div class="box box-primary">
                                <div class="box-body box-profile">
                                    <ul>
                                        <li id="folder-mau" style="display:none"> <i class="fa fa-fw fa-folder-open"></i><span class="folder-name">Ten</span></li>
                                        @{
                                            var users = _userHelper.GetCurrentUserAsync().Result.Id;
                                            var folders = _folderRepo.GetAll().Where(r => r.IdNguoiTao == users);
                                            var countFolder = 1;
                                            var idFirstFolder = 0;
                                            foreach (var item in folders)
                                            {
                                                <li class="@(countFolder == 1 ? "folder-active" : "")" data-id="@item.Id"><i class="fa fa-fw fa-folder-open"></i><span class="folder-name">@item.Ten</span></li>
                                                if (countFolder == 1)
                                                {
                                                    idFirstFolder = item.Id;
                                                }
                                                countFolder++;
                                            }
                                        }

                                        <li>
                                            <div style="max-width:100%">
                                                <label for="input-name-folder">
                                                    <a href="javascript:void(0)" id="add-folder">+</a>
                                                </label>
                                                <input type="text" class="" name="input-name-folder" id="input-name-folder" style="display:none" />
                                            </div>

                                        </li>
                                    </ul>
                                </div>
                                <!-- /.box-body -->
                            </div>
                            <!-- /.box -->

                        </div>
                        <!-- /.col -->
                        <div class="col-md-9" id="binding-list-file">
                            @await Component.InvokeAsync("FileInFolder", new { folderId = idFirstFolder })
                            <!-- /.nav-tabs-custom -->
                        </div>
                        <!-- /.col -->
                    </div>
                    <!-- /.row -->

                </section>
                <!-- /.content -->
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger pull-left" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-success" id="dinh-kem-file">Đính kèm</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>

</div>